provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
  extraEnv:
    - name: QUERY_BASE_PATH
      value: /jaeger
    - name: METRICS_STORAGE_TYPE
      value: prometheus
    - name: SPAN_STORAGE_TYPE
      value: memory
    - name: COLLECTOR_ZIPKIN_HOST_PORT
      value: :9411
    - name: JAEGER_DISABLED
      value: "false"
    - name: COLLECTOR_OTLP_ENABLED
      value: "true"
    
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 128Mi  
storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
