mode: deployment
image:
 repository: otel/opentelemetry-collector
 tag: "latest"
 
command:
 name: otelcol
config:
 receivers:
   otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
            endpoint: ${env:MY_POD_IP}:4318 
   prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
           
 exporters:   
   otlp:
      endpoint: 'jaeger-collector.connectingtokabi-dev.svc.cluster.local:4317'
      tls:
          insecure: true
   logging:
     loglevel: debug
   prometheus:
        enable_open_metrics: true
        endpoint: ${env.MY_POD_IP}:9464
        resource_to_telemetry_conversion:
          enabled: true 
        
 service:
   telemetry:
     logs:
       level: debug
     metrics:
          address: ${env:MY_POD_IP}:8888  
   pipelines:
     traces:
       receivers:
         - otlp
       processors:
         - batch  
       exporters:        
         - otlp
         #- logging
     metrics: 
        exporters:         
          - prometheus
         # - logging
        processors:
           - batch
        receivers:
         - otlp 
     logs: null
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    # nodePort: 30317
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  jaeger-compact:
    enabled: true
    containerPort: 6831
    servicePort: 6831
    hostPort: 6831
    protocol: UDP
  jaeger-thrift:
    enabled: true
    containerPort: 14268
    servicePort: 14268
    hostPort: 14268
    protocol: TCP
  jaeger-grpc:
    enabled: true
    containerPort: 14250
    servicePort: 14250
    hostPort: 14250
    protocol: TCP
  zipkin:
    enabled: true
    containerPort: 9411
    servicePort: 9411
    hostPort: 9411
    protocol: TCP
  metrics:
    # The metrics port is disabled by default. However you need to enable the port
    # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP 
  prometheus: 
      enabled: true
      containerPort: 9464
      servicePort: 9464
      protocol: TCP
    
     